export const UI_STRINGS = {
  SHOWCASE_LABEL: 'Showcase Mode',
  MUTE_LABEL: 'Mute Sounds',
  UNMUTE_LABEL: 'Unmute Sounds',
  EXPORT_LABEL: 'Share My Server Room',
  SCENE_COLORS_LABEL: 'Scene Colors',
  SCENE_COLORS_SUBTITLE: 'Controls server room scene only',
  PRESET_LABEL: 'Presets',
  RESET_PRESET_LABEL: 'Reset to Preset',
  SAVE_CUSTOM_LABEL: 'Save Custom',
  COLOR_FLOOR: 'Floor',
  COLOR_WALL: 'Wall',
  COLOR_CEILING: 'Ceiling',
  COLOR_AMBIENT: 'Ambient',
  COLOR_RACK_BODY: 'Rack Body',
  COLOR_RACK_TRIM: 'Rack Trim',
  COLOR_LED_IDLE: 'LED Idle',
  COLOR_LED_ACTIVE: 'LED Active',
  COLOR_LED_ERROR: 'LED Error',
  COLOR_CABLE_A: 'Cable A',
  COLOR_CABLE_B: 'Cable B',
  COLOR_SCREEN_BG: 'Screen BG',
  COLOR_SCREEN_TEXT: 'Screen Text',
  COLOR_ACCENT_A: 'Accent A',
  COLOR_ACCENT_B: 'Accent B',
  COLOR_SHADOW: 'Shadow',
  CONTAINER_DETAIL_TITLE: 'Container Detail',
  CLOSE_LABEL: 'Close',
  DEMO_MODE_LABEL: 'Virtual Fleet (Showcase)',
  VOLUME_LABEL: 'Volume',
} as const;
